#!/usr/bin/env bash
echo "== deploy s3 bucket via CFM"

STACK_NAME="cfm-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset
--region us-west-2 \
--stack-name $STACK_NAME