#! /usr/bin/env bash
echo "== list objects"

# Check if at least one argument is provided
if [ -z "$1" ]; then
    echo "There needs to be a bucket name e.g., ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

# https://docs.aws.amazon.com/cli/latest/reference/s3control/create-bucket.html
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME 
